---
abstract: 'Business Time Between Two Times'
author:
  - 'David Peters (davidp@electronf.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Business
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
version: 0.18
